apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/argocd.yaml
  - apps/cmatrix.yaml
  - apps/chatbot.yaml
  - apps/notes-app.yaml
  - apps/gpu-observability.yaml
  - apps/space-invaders.yaml
