apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmatrix
  namespace: default
  labels:
    app: cmatrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmatrix
  template:
    metadata:
      labels:
        app: cmatrix
    spec:
      containers:
        - name: cmatrix
          image: localhost:32000/cmatrix:novnc2
          imagePullPolicy: Always
          ports:
            - containerPort: 6080
              name: novnc
