apiVersion: v1
kind: Service
metadata:
  name: cmatrix
  namespace: default
spec:
  type: NodePort
  selector:
    app: cmatrix
  ports:
    - name: novnc
      protocol: TCP
      port: 6080
      targetPort: novnc
      nodePort: 30081
